# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [1]:
import numpy as np
np.version.version

'2.0.2'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [2]:
# Напишите ваш код здесь
import numpy as np

arr = np.random.randint(-1000, 1000, size=(10,10))

print(arr)

print("\nMin - " + str(np.min(arr)))
print("Max - " + str(np.max(arr)))

[[-421 -213 -191  -46  647  534 -819   35  146 -991]
 [  66  127  525  466 -129 -884  949 -556  697 -404]
 [ 338 -132 -775  -19 -259 -941  165  784 -892 -411]
 [-279 -450 -509 -430 -239  993 -386 -324  722   37]
 [ 808  -76  106  580 -952  280 -502 -903  234  635]
 [ 221   60  701 -176  766   46  537 -245 -843 -614]
 [  43 -783 -883  572 -891 -704 -890   33 -433 -892]
 [ 111 -712  775  271 -347 -460  495 -497  181  233]
 [ -82  312 -735 -385  584 -424  369 -173 -485  -15]
 [ 100  252 -101 -557  140 -993  149  602 -816  953]]

Min - -993
Max - 993


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [3]:
# Напишите ваш код здесь
import numpy as np

size = 8

arr = np.zeros((size,size))

for i in range(size):
  for j in range(size):
    if i % 2 != 0 and j % 2 != 0:
      continue
    if i % 2 != 0 or j % 2 != 0:
      arr[i,j] = 1

print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [4]:
# Напишите ваш код здесь
import numpy as np

z = np.arange(11)

print("Исходный массив:" + str(z))

for i in range(z.size):
  if z[i] > 3 and z[i] < 8:
    z[i] *= -1

print("Итоговый массив:" + str(z))

Исходный массив:[ 0  1  2  3  4  5  6  7  8  9 10]
Итоговый массив:[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [5]:
# Напишите ваш код здесь
import numpy as np

z = np.random.rand(5, 10)
average = np.mean(z, axis=1, keepdims=True)

print("Исходный массив\n" + str(z))
print("\nСреднее арифметическое\n" + str(average) + "\n")

print("Итоговый массив: \n" + str(np.subtract(z, average)))

Исходный массив
[[0.0111023  0.21555788 0.32934717 0.30089699 0.28206684 0.74350083
  0.12702615 0.31893849 0.43164443 0.72622935]
 [0.62998273 0.92227176 0.13893122 0.2539381  0.929057   0.06395431
  0.54666987 0.39963247 0.68471954 0.85562852]
 [0.70919801 0.32265796 0.88336665 0.57982098 0.11741156 0.14835377
  0.95360759 0.73603931 0.20125727 0.17979991]
 [0.37478237 0.89632914 0.39440803 0.57731357 0.73489414 0.38552776
  0.26699847 0.11634343 0.16452964 0.4259574 ]
 [0.29191524 0.748007   0.49693184 0.01411176 0.56636687 0.57226956
  0.78867917 0.09086432 0.78533367 0.56332529]]

Среднее арифметическое
[[0.34863104]
 [0.54247855]
 [0.4831513 ]
 [0.43370839]
 [0.49178047]]

Итоговый массив: 
[[-0.33752874 -0.13307317 -0.01928387 -0.04773406 -0.0665642   0.39486979
  -0.22160489 -0.02969255  0.08301339  0.37759831]
 [ 0.08750418  0.37979321 -0.40354733 -0.28854045  0.38657845 -0.47852425
   0.00419132 -0.14284608  0.14224099  0.31314997]
 [ 0.22604671 -0.16049334  0.40021535  0.096

5. Поменяйте 1 и 2 строки матрицы

In [6]:
# Напишите ваш код здесь
import numpy as np

z = np.arange(25).reshape(5,5)
print("Исходное:\n" + str(z))

tmp = z[0][:].copy()
z[0][:] = z[1][:]
z[1][:] = tmp

print("\nИтог:\n" + str(z))

Исходное:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Итог:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [7]:
# Ваш код здесь
import numpy as np
import math

z = np.random.random((10,2))
res = z.copy()

res[:, 0] = np.sqrt(np.square(z[:, 0]) + np.square(z[:, 1]))
res[:, 1] = np.arctan2(z[:, 1], z[:, 0])

print("Исходное:\n", z)
print("\nРезультат (r, theta):\n", res)

# Ваш код здесь

Исходное:
 [[0.54743639 0.22269497]
 [0.70825753 0.15926623]
 [0.32860686 0.13084952]
 [0.69832238 0.21219618]
 [0.04221011 0.82486449]
 [0.29761585 0.47714891]
 [0.90544745 0.90453537]
 [0.50924124 0.48861474]
 [0.68475002 0.93295178]
 [0.67050752 0.51764994]]

Результат (r, theta):
 [[0.59099886 0.3863513 ]
 [0.72594384 0.22119118]
 [0.35370053 0.37894914]
 [0.72985023 0.29499948]
 [0.82594378 1.51966875]
 [0.56235778 1.01310511]
 [1.27985129 0.78489424]
 [0.70574146 0.7647303 ]
 [1.15727335 0.93763959]
 [0.84707839 0.65745003]]


7. Заменить максимальный элемент массива на ноль

In [8]:
# Ваш код здесь
import numpy as np

z = np.random.random(10)
max = z.max()

print("Максимум:", max)
print("\nИсходное:\n", z)

z[(np.where(z == max))] = 0

print("\nРезультат:\n", z)

Максимум: 0.933820007910392

Исходное:
 [0.69381037 0.41600609 0.65328672 0.48600967 0.00476952 0.73965607
 0.93382001 0.58229638 0.87154992 0.24388405]

Результат:
 [0.69381037 0.41600609 0.65328672 0.48600967 0.00476952 0.73965607
 0.         0.58229638 0.87154992 0.24388405]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [9]:
# Напишите ваш код здесь
import numpy as np

z = np.ones(10)
i = np.random.randint(0,len(z),20)
chk = ""

print("Первый массив:\n", z)
print("\nВторой массив:\n", i)

for char in i:
  if str(char) in chk:
    continue
  else:
    z[char] += 1
    chk += str(char)

print("\nРезультат:\n", z)

Первый массив:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Второй массив:
 [7 4 1 7 6 6 8 7 9 2 7 5 3 3 0 8 0 3 1 3]

Результат:
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [10]:
# Напишите ваш код здесь
import numpy as np

z = np.array([1,2,3,4,5])
result = []

for i in range(z.size - 1):
    result.append(int(z[i]))
    result.append(0)
    result.append(0)
    result.append(0)

result.append(int(z[z.size-1]))

arr = np.array(result)
print("Исходное:\n", z)
print("\nРезультат:\n", result)

Исходное:
 [1 2 3 4 5]

Результат:
 [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [11]:
# Напишите ваш код здесь
import numpy as np

z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
chk = v - int(v)

print("Массив:\n", z)
print("Исходное число:\n", v)

print((z[int(v)], z[int(v) + 1])[chk > 0.5])

Массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Исходное число:
 15.050773517838934
15


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?